<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\pigeon_walking-Sheet.png" />
      <Content Include="Resources\pigeon_walking-Sheet.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Resources\Crow.png" />
      <Content Include="Resources\Crow.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Resources\pigeon_eat-Sheet.png" />
      <Content Include="Resources\pigeon_eat-Sheet.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
<None Remove="Resources\pigeon_fiy-Sheet.png" />
      <Content Include="Resources\pigeon_fiy-Sheet.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Resources\Background.png" />
      <Content Include="Resources\Background.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Resources\nest.svg" />
      <None Remove="Resources\nest.png" />
      <Content Include="Resources\nest.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
